### ISSUE TITLE
Can not create a new container from an image

### ISSUE THREAD

**Issue by toabctl** [containers/python-podman#33]
With python3.7 and podman installed from git in a virtualenv:

```
# cat reproducer.py 
import podman

with podman.Client() as client:
    image_id = client.images.pull('registry.hub.docker.com/opensuse/leap:15.1')
    image = client.images.get(image_id)
    image.create(command=['/usr/bin/top'])
```

I get:

```
# python3 reproducer.py 
Traceback (most recent call last):
  File "reproducer.py", line 6, in <module>
    image.create(command=['/usr/bin/top'])
  File ".tox/py37/lib/python3.7/site-packages/podman/libs/images.py", line 53, in create
    id_ = podman.CreateContainer(config)['container']
  File ".tox/py37/lib/python3.7/site-packages/varlink/client.py", line 86, in _wrapped
    return self._call(method.name, *args, **kwargs)
  File ".tox/py37/lib/python3.7/site-packages/varlink/client.py", line 143, in _call
    (message, more) = self._next_varlink_message()
  File ".tox/py37/lib/python3.7/site-packages/varlink/client.py", line 104, in _next_varlink_message
    message = next(self._next_message())
  File ".tox/py37/lib/python3.7/site-packages/varlink/client.py", line 265, in _next_message
    raise BrokenPipeError("Disconnected")
BrokenPipeError: Disconnected

```

**Comment by toabctl** [comment]
The same happens when running the example from https://github.com/containers/python-podman/blob/master/examples/eg_attach.py
