### ISSUE TITLE
pypodman for WINDOWS: No module named 'fcntl' 

### ISSUE THREAD

**Issue by Edward5hen** [containers/python-podman#4]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 # **kind bug**

**Description**
I'm trying to use `pypodman` on windows. It's said module 'fcntl' is not found. As I know, this module is not available on windows, we should use some other package to replace it.
https://github.com/containers/libpod/blob/7f91ebb441846bc5a9c44861c70bec66b9015fa3/contrib/python/podman/podman/libs/_containers_attach.py#L4

**Steps to reproduce the issue:**
On my windows10 VM:
1. install varlink

2. install podman package following:
```
cd ~/libpod/contrib/python/podman
python3 setup.py clean -a && python3 setup.py sdist bdist
python3 setup.py install --user
```

3. `python3 -c "import podman"`

**Describe the results you received:**
```
C:\Users\edward\work>python -c "import podman"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\edward\AppData\Roaming\Python\Python36\site-packages\podman-0.0.0-py3.6.egg\podman\__init__.py", line 4, in <module>
  File "C:\Users\edward\AppData\Roaming\Python\Python36\site-packages\podman-0.0.0-py3.6.egg\podman\client.py", line 11, in <module>
  File "C:\Users\edward\AppData\Roaming\Python\Python36\site-packages\podman-0.0.0-py3.6.egg\podman\libs\containers.py", line 10, in <module>
  File "C:\Users\edward\AppData\Roaming\Python\Python36\site-packages\podman-0.0.0-py3.6.egg\podman\libs\_containers_attach.py", line 4, in <module>
ModuleNotFoundError: No module named 'fcntl'
```

**Describe the results you expected:**
podman package can be used on windows smoothly.

**Comment by rhatdan** [comment]
@Edward5hen We are moving to podman-remote which is a go based application to run on Windows and Mac.
