### ISSUE TITLE
Search function throws 'no attribute SearchImage' error

### ISSUE THREAD

**Issue by renuHadke** [containers/python-podman#47]
Encountered the below error while trying to search a particular image by id_ using search functionality ```search(self, id_, limit=25)```

```
Traceback (most recent call last):
  File "sdk.py", line 9, in <module>
    for eln in img:
  File "/root/.local/lib/python3.7/site-packages/podman/libs/images.py", line 156, in search
    results = podman.SearchImage(id_, limit)
AttributeError: 'SimpleClientInterfaceHandler' object has no attribute 'SearchImage'
```

**Comment by rhatdan** [comment]
Would you be interested in opening a PR to fix this?

**Comment by renuHadke** [comment]
I am working on resolving this and will raise a PR when it is fixed.
