### ISSUE TITLE
Call host podman inside a container but encounter `Connection refused` error

### ISSUE THREAD

**Issue by lcnsir** [containers/python-podman#57]
I want to call host podman inside a container by podman python client

So I do
1.  run a contianer and mount podman socket
`podman run -it --privileged --entrypoint=bash -v /lib/systemd/system/io.podman.socket:/lib/systemd/system/io.podman.socket docker.io/python:3.6`

2.  then I login to the container, install python package
`python3 -m pip install podman`

3. call podman with the socket `unix:/lib/systemd/system/io.podman.socket` like what I did with docker but error shows
```
python
Python 3.6.9 (default, Sep 12 2019, 16:23:48)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import podman
>>> pclient=podman.Client(uri='unix:/lib/systemd/system/io.podman.socket')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/podman/client.py", line 178, in __init__
    if not System(self._client).ping():
  File "/usr/local/lib/python3.6/site-packages/podman/libs/system.py", line 38, in ping
    with self._client() as podman:
  File "/usr/local/lib/python3.6/site-packages/podman/client.py", line 98, in __enter__
    self._iface = self._client.open(self._context.interface)
  File "/usr/local/lib/python3.6/site-packages/varlink/client.py", line 598, in open
    connection = self.open_connection()
  File "/usr/local/lib/python3.6/site-packages/varlink/client.py", line 613, in open_connection
    return self._socket_fn()
  File "/usr/local/lib/python3.6/site-packages/varlink/client.py", line 512, in open_unix
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by lcnsir** [comment]
Anyone can help me on this, about I could I call host podman like what we did with docker

**Comment by TomSweeneyRedHat** [comment]
I think you're trying this as a rootless user?  If so, ping won't work inside of the container without further admin changes.  Can you confirm you try this as root and see if it works?  Here's a [ptr](https://github.com/containers/libpod/blob/master/troubleshooting.md#5-rootless-containers-cannot-ping-hosts) to allow ping to work rootless if that's the issue.

**Comment by rhatdan** [comment]
A couple of things.  First is the podman on the server, new enough.  I think it has to be at least podman 1.5 or newer.  Second, this should only work if you are running rootfull podman not rootless.

**Comment by lcnsir** [comment]
@TomSweeneyRedHat I'm trying as a root user.  it working in podman 1.6 but not working on podman 1.02

**Comment by lcnsir** [comment]
Thanks @rhatdan it seems podman varlink issue.

**Comment by 4383** [comment]
Hello @lcnsir 

Can tell me more about the varlink issue that you observe?

**Comment by lcnsir** [comment]
@4383  I want to call host podman inside a container that mount the socket in the container that I did in 
https://github.com/containers/python-podman/issues/57#issuecomment-540995108

Then Call podman socket by the python client

When  podman  version 

is 

```
root@swagman3:~# podman version
Version:            1.6.1
RemoteAPI Version:  1
Go Version:         go1.10.4
OS/Arch:            linux/amd64
```
on a ubuntu host, it successfully


when the podman version is 
```
[root@worker1 core]# podman version
Version:       1.0.2-dev
Go Version:    go1.11.5
OS/Arch:       linux/amd64
```

it failed with error 
```
>>> pclient=podman.Client()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/podman/client.py", line 178, in __init__
    if not System(self._client).ping():
  File "/usr/local/lib/python3.6/site-packages/podman/libs/system.py", line 38, in ping
    with self._client() as podman:
  File "/usr/local/lib/python3.6/site-packages/podman/client.py", line 98, in __enter__
    self._iface = self._client.open(self._context.interface)
  File "/usr/local/lib/python3.6/site-packages/varlink/client.py", line 598, in open
    connection = self.open_connection()
  File "/usr/local/lib/python3.6/site-packages/varlink/client.py", line 613, in open_connection
    return self._socket_fn()
  File "/usr/local/lib/python3.6/site-packages/varlink/client.py", line 512, in open_unix
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by jwhonce** [comment]
@lcnsir I don't believe remote access was supported until [podman 1.1.0](https://github.com/containers/libpod/releases/tag/v1.1.0)

**Comment by rhatdan** [comment]
So can we close this as not an issue?

**Comment by lcnsir** [comment]
yes pls close it, thanks guys
